# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/personal/projects/githubproj/Game/Pong

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/personal/projects/githubproj/Game/Pong

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/personal/projects/githubproj/Game/Pong/CMakeFiles /mnt/c/personal/projects/githubproj/Game/Pong/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/personal/projects/githubproj/Game/Pong/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PongGame

# Build rule for target.
PongGame: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PongGame
.PHONY : PongGame

# fast build rule for target.
PongGame/fast:
	$(MAKE) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/build
.PHONY : PongGame/fast

ball.o: ball.cpp.o

.PHONY : ball.o

# target to build an object file
ball.cpp.o:
	$(MAKE) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/ball.cpp.o
.PHONY : ball.cpp.o

ball.i: ball.cpp.i

.PHONY : ball.i

# target to preprocess a source file
ball.cpp.i:
	$(MAKE) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/ball.cpp.i
.PHONY : ball.cpp.i

ball.s: ball.cpp.s

.PHONY : ball.s

# target to generate assembly for a file
ball.cpp.s:
	$(MAKE) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/ball.cpp.s
.PHONY : ball.cpp.s

game.o: game.cpp.o

.PHONY : game.o

# target to build an object file
game.cpp.o:
	$(MAKE) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/game.cpp.o
.PHONY : game.cpp.o

game.i: game.cpp.i

.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s

.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/game.cpp.s
.PHONY : game.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/main.cpp.s
.PHONY : main.cpp.s

paddle.o: paddle.cpp.o

.PHONY : paddle.o

# target to build an object file
paddle.cpp.o:
	$(MAKE) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/paddle.cpp.o
.PHONY : paddle.cpp.o

paddle.i: paddle.cpp.i

.PHONY : paddle.i

# target to preprocess a source file
paddle.cpp.i:
	$(MAKE) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/paddle.cpp.i
.PHONY : paddle.cpp.i

paddle.s: paddle.cpp.s

.PHONY : paddle.s

# target to generate assembly for a file
paddle.cpp.s:
	$(MAKE) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/paddle.cpp.s
.PHONY : paddle.cpp.s

score.o: score.cpp.o

.PHONY : score.o

# target to build an object file
score.cpp.o:
	$(MAKE) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/score.cpp.o
.PHONY : score.cpp.o

score.i: score.cpp.i

.PHONY : score.i

# target to preprocess a source file
score.cpp.i:
	$(MAKE) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/score.cpp.i
.PHONY : score.cpp.i

score.s: score.cpp.s

.PHONY : score.s

# target to generate assembly for a file
score.cpp.s:
	$(MAKE) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/score.cpp.s
.PHONY : score.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... PongGame"
	@echo "... ball.o"
	@echo "... ball.i"
	@echo "... ball.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... paddle.o"
	@echo "... paddle.i"
	@echo "... paddle.s"
	@echo "... score.o"
	@echo "... score.i"
	@echo "... score.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

